// Barbara's Academy of Dance — genre education content
const GENRES = [
  { id: "ballet", name: "Ballet", origin: "Italian courts, 15th c. → France & Russia", era: "c. 1450",
    tagline: "The foundation of Western concert dance — taught here in the Russian tradition.",
    history: "Ballet began as court entertainment in Renaissance Italy and was formalized in France under Louis XIV, who founded the first dance academy in 1661 — which is why its vocabulary is French. The 19th century brought pointe work and the romantic tutu; Russian training carried it to its height. Our studio teaches the Vaganova method — the Russian system built on careful progression, expressive port de bras and whole-body coordination.",
    looks: "Turned-out legs, pointed feet, vertical posture and long lines. Movement is codified: every step has a name, a shape and a correct execution. Classes follow a fixed arc — barre, centre, adagio, turns, jumps.",
    music: "Classical orchestral scores — Tchaikovsky, Delibes, Prokofiev — and piano accompaniment in class.",
    expect: "Leotard and tights, hair secured, ballet slippers. Classes follow the Vaganova syllabus level by level — expect structure, repetition and steady measurable progress.",
    why: "Ballet builds the alignment, strength and vocabulary every other genre borrows from. Most serious dancers in any style train ballet alongside it.",
    vocab: [
      { term: "Plié", origin: "French — “bent”", level: "Beginner", desc: "A bending of the knees with hips, legs and feet turned out. The foundation of every jump and landing." },
      { term: "Tendu", origin: "French — “stretched”", level: "Beginner", desc: "The working foot slides from first or fifth position to a full point without leaving the floor." },
      { term: "Arabesque", origin: "French", level: "Intermediate", desc: "Standing on one leg with the other extended straight behind, arms in a long line." },
      { term: "Pirouette", origin: "French — “whirl”", level: "Intermediate", desc: "A complete turn of the body on one foot, on pointe or demi-pointe." },
      { term: "Grand jeté", origin: "French — “big throw”", level: "Advanced", desc: "A large leap forward with legs at full split at the height of the jump." } ] },
  { id: "pointe", name: "Pointe", origin: "Romantic ballet, France & Italy", era: "c. 1830s",
    tagline: "Ballet, elevated — literally.",
    history: "Dancing on the tips of the toes emerged in the Romantic era — Marie Taglioni's 1832 La Sylphide made the floating, ethereal ballerina the ideal — and stiffened, blocked shoes evolved through the Italian and Russian schools to make sustained pointe work possible.",
    looks: "Classical ballet vocabulary performed en pointe: hops, relevés, turns and balances on a platform the size of a few coins. Strength is invisible; the effect is weightlessness.",
    music: "The classical ballet repertoire — pointe class extends ballet class, not replaces it.",
    expect: "By teacher approval only, after a strength and alignment assessment (typically age 11+ with several years of Vaganova training). Professionally fitted shoes are essential — we'll guide the first fitting.",
    why: "Pointe is the goal that focuses serious ballet training — and the clearest reward for years of careful technique.",
    vocab: [
      { term: "Relevé", origin: "French — “raised”", level: "Beginner", desc: "Rising from flat feet to the platform of the shoe, through the demi-pointe." },
      { term: "Échappé", origin: "French — “escaped”", level: "Beginner", desc: "A spring from fifth position out to second, landing on both pointes." },
      { term: "Bourrée", origin: "French", level: "Intermediate", desc: "Tiny, even steps on pointe that make the dancer appear to glide." },
      { term: "Fouetté", origin: "French — “whipped”", level: "Advanced", desc: "Repeated turns powered by a whipping leg — 32 of them is ballet's most famous feat." } ] },
  { id: "jazz", name: "Jazz", origin: "African-American vernacular dance, USA", era: "c. 1910s",
    tagline: "Energy, syncopation and performance polish.",
    history: "Jazz dance grew from African-American social dances of the early 20th century — the Charleston, Lindy Hop and tap-adjacent vernacular forms — and was theatricalized on Broadway and in Hollywood. Choreographers like Jack Cole, Katherine Dunham and Bob Fosse shaped the studio style taught today.",
    looks: "Sharp, syncopated, grounded movement with bent knees and isolations of the head, shoulders, ribs and hips. Big kicks, turns, leaps and unmistakable performance energy.",
    music: "Historically jazz and swing; today's classes use musical theatre, pop and funk.",
    expect: "Fitted dancewear and jazz shoes or half-soles. Classes open with a stylized warm-up and isolations, build technique across the floor, and finish with combination work.",
    why: "Jazz teaches musicality, dynamics and stage presence — it's the backbone of musical theatre and commercial dance work.",
    vocab: [
      { term: "Isolation", origin: "Jazz technique", level: "Beginner", desc: "Moving one part of the body — head, shoulders, ribs, hips — independently of the rest." },
      { term: "Ball change", origin: "American jazz", level: "Beginner", desc: "A quick two-count weight transfer — ball of one foot, then flat of the other." },
      { term: "Jazz square", origin: "American jazz", level: "Beginner", desc: "Four steps tracing a square: cross, back, side, front." },
      { term: "Fan kick", origin: "American jazz", level: "Intermediate", desc: "A straight leg sweeps in a full arc across the body, hips level." },
      { term: "Calypso", origin: "American jazz", level: "Advanced", desc: "A turning leap with the front leg in attitude and the back leg extended." } ] },
  { id: "hip-hop", name: "Hip-Hop", origin: "The Bronx, New York", era: "c. 1973",
    tagline: "Groove first. Foundation always.",
    history: "Hip-hop dance was born at Bronx block parties in the early 1970s alongside DJing, MCing and graffiti. Breaking came first; funk styles from the West Coast — popping and locking — joined the culture, and party dances and choreography styles evolved with each era of the music.",
    looks: "Grounded, groove-driven movement riding the beat: bounces and rocks, crisp hits, footwork and freezes. Individual style matters as much as the steps — cyphers and battles are part of the culture.",
    music: "Hip-hop, funk and breakbeats — the music and the dance are inseparable.",
    expect: "Sneakers and comfortable street clothes you can move in. Classes build grooves and foundation steps first, then combine them into choreography. No prior experience needed.",
    why: "Hip-hop develops rhythm, weight and individuality — and it's the most immediately social and improvisational genre we teach.",
    vocab: [
      { term: "Bounce", origin: "Foundations", level: "Beginner", desc: "The continuous groove in the knees and chest that everything else rides on." },
      { term: "Top rock", origin: "Breaking", level: "Beginner", desc: "Upright footwork patterns that open a breaking set." },
      { term: "Six-step", origin: "Breaking", level: "Intermediate", desc: "The core downrock pattern — six counts circling the body on the floor." },
      { term: "Popping", origin: "Funk styles (Fresno, CA)", level: "Intermediate", desc: "Quick contraction and release of muscles to hit sharply on the beat." },
      { term: "Freeze", origin: "Breaking", level: "Intermediate", desc: "A sudden held shape — often balanced on hands, head or shoulder — punctuating a set." } ] },
  { id: "tap", name: "Tap", origin: "African-American & Irish fusion, USA", era: "c. 1840s",
    tagline: "The dancer is the instrument.",
    history: "Tap emerged in 19th-century America where African rhythmic dance met Irish step dancing. It flourished in vaudeville and Hollywood — Bill “Bojangles” Robinson, the Nicholas Brothers, Fred Astaire — and lives on in both rhythm tap (music first) and Broadway tap (spectacle first).",
    looks: "Percussive footwork in metal-plated shoes: the dancer produces the music. Weight stays low and relaxed; complexity comes from layering sounds, not from height or lines.",
    music: "Jazz standards and swing, or nothing at all — a cappella tap is its own tradition.",
    expect: "Tap shoes (rental/loaner pairs available for first-timers) and anything comfortable. Classes build sounds from single steps into rhythmic phrases and time steps.",
    why: "Tap is the fastest route to real musicianship — dancers learn rhythm, phrasing and improvisation the way instrumentalists do.",
    vocab: [
      { term: "Shuffle", origin: "Rhythm tap", level: "Beginner", desc: "A brush forward and back with the ball of the foot — two sounds." },
      { term: "Flap", origin: "Rhythm tap", level: "Beginner", desc: "Brush forward then step — two sounds, traveling." },
      { term: "Cramp roll", origin: "Rhythm tap", level: "Intermediate", desc: "Toe-toe-heel-heel in quick succession — four distinct sounds." },
      { term: "Time step", origin: "Rhythm tap", level: "Intermediate", desc: "A repeating rhythmic phrase traditionally used to set tempo with the band." },
      { term: "Wings", origin: "Rhythm tap", level: "Advanced", desc: "A jump where the feet scrape out and in, producing multiple sounds mid-air." } ] },
  { id: "contemporary", name: "Contemporary", origin: "Modern-dance lineage, USA & Europe", era: "c. 1950s",
    tagline: "Gravity, breath and honest movement.",
    history: "Contemporary descends from the modern-dance rebels — Martha Graham, Doris Humphrey, Merce Cunningham — who rejected ballet's constraints in the early 20th century. Release technique, floor work and contact improvisation shaped today's hybrid concert style.",
    looks: "Bare feet, articulate spines, work in and out of the floor. Movement uses gravity and momentum rather than fighting them; shapes can be beautiful, awkward, or both on purpose.",
    music: "Anything — ambient, indie, spoken word, silence. The score serves the idea.",
    expect: "Bare feet or foot undies, fitted clothes that allow floor work. Classes blend technique (often Graham or release-based), traveling phrases and expressive combination work.",
    why: "Contemporary builds versatility and artistry — it's where dancers learn to make choices, not just execute steps.",
    vocab: [
      { term: "Contraction", origin: "Graham technique", level: "Beginner", desc: "A deep curve of the spine initiated from the pelvis, on the exhale." },
      { term: "Release", origin: "Release technique", level: "Beginner", desc: "Letting go of muscular tension so movement follows momentum and breath." },
      { term: "Spiral", origin: "Graham technique", level: "Intermediate", desc: "Rotation of the torso around the spine, connecting floor work to standing." },
      { term: "Floor slide", origin: "Release technique", level: "Intermediate", desc: "Momentum carried into the floor through a controlled slide, weight into the hands." } ] },
  { id: "lyrical", name: "Lyrical", origin: "Studio & competition culture, USA", era: "c. 1980s",
    tagline: "Ballet's line, jazz's drive, the song's story.",
    history: "Lyrical developed in American studio and competition culture as choreographers fused ballet and jazz technique to interpret the lyric of a song. It borrows contemporary's emotional range while keeping jazz's clarity and ballet's line.",
    looks: "Flowing, sustained movement that rides the phrase of the music rather than the count — long extensions, expressive port de bras, seamless transitions, storytelling faces.",
    music: "Vocal-driven pop and ballads — the lyric is the choreography's script.",
    expect: "Bare feet or half-soles, fitted dancewear. Ballet or jazz basics help; the class emphasizes emotional interpretation as much as technique.",
    why: "Lyrical teaches dancers to connect technique to feeling — the interpretive skill competitions and choreographers prize most.",
    vocab: [
      { term: "Sustained balance", origin: "Lyrical", level: "Beginner", desc: "A held extension riding the phrase of the music rather than the count." },
      { term: "Fall and recover", origin: "Humphrey technique", level: "Intermediate", desc: "Yielding to gravity off balance, then rebounding through the breath." },
      { term: "Illusion", origin: "Lyrical / jazz", level: "Advanced", desc: "A vertical windmill of the body — the standing leg pivots as the working leg sweeps a full circle." } ] },
  { id: "acro", name: "Acro", origin: "Circus & vaudeville acrobatics + dance", era: "c. 1900s",
    tagline: "Where dance technique meets acrobatic skill.",
    history: "Acrobatic dance grew out of vaudeville and circus performance in the early 20th century, where flexible 'contortion' acts shared bills with dancers. Modern acro codifies that fusion: acrobatic tricks trained safely and woven into dance choreography.",
    looks: "Balances, walkovers, aerials and contortion elements blended seamlessly with dance — a trick should arrive and leave like a dance step, not a gymnastics pass.",
    music: "Whatever the choreography calls for — acro lives inside jazz, lyrical and contemporary pieces.",
    expect: "Bare feet, fitted clothes, hair secured. Skills progress strictly in order — backbends before walkovers, walkovers before aerials — with hands-on spotting at every step.",
    why: "Acro builds strength, flexibility and body control that pay off in every other genre — and kids love the visible milestones.",
    vocab: [
      { term: "Bridge", origin: "Acro foundations", level: "Beginner", desc: "A backbend from the floor, hands and feet planted — the base of all back flexibility skills." },
      { term: "Cartwheel", origin: "Acro foundations", level: "Beginner", desc: "A sideways rotation through a handstand, landing one foot at a time." },
      { term: "Walkover", origin: "Acro", level: "Intermediate", desc: "A slow, controlled rotation through a handstand and bridge, forward or back." },
      { term: "Aerial", origin: "Acro", level: "Advanced", desc: "A cartwheel with no hands — full rotation in the air." } ] },
  { id: "preschool", name: "Preschool Combo", origin: "Early-childhood dance education", era: "Ages 3–5",
    tagline: "First steps — ballet, tap and tumbling in one class.",
    history: "Combination classes are how generations of dancers have started: short segments of ballet, tap and creative movement in a single weekly class, built around how preschoolers actually learn — imagination, imitation and play.",
    looks: "Story-driven movement, prop work, freeze dances and simple across-the-floor patterns. Underneath the play: rhythm, balance, following directions and classroom skills.",
    music: "Playful, age-appropriate songs with strong, clear beats.",
    expect: "Any leotard and tights or comfy clothes; ballet shoes and tap shoes (loaners available). Caregivers wait in the lobby — independence is part of the curriculum. 45 minutes, lots of smiles.",
    why: "It's the gentlest on-ramp into dance — kids discover which genres they love before committing to one.",
    vocab: [
      { term: "First position", origin: "Ballet", level: "Beginner", desc: "Heels together, toes turned out — the first shape every dancer learns." },
      { term: "Tippy toes", origin: "Ballet (relevé)", level: "Beginner", desc: "Rising up high on the balls of the feet — baby relevé." },
      { term: "Heel digs", origin: "Tap", level: "Beginner", desc: "Tapping the heel of the shoe on the floor to make a sound on the beat." },
      { term: "Freeze dance", origin: "Creative movement", level: "Beginner", desc: "Dance while the music plays, hold a shape when it stops — balance in disguise." } ] }
];
module.exports = { GENRES };
